stages:
  - test
  - terraform
  - deploy

default:
  image: alpine:latest
  before_script:
    - apk add --no-cache bash curl gettext
    - chmod +x ./scripts/*.sh

security-scan:
  stage: test
  script:
    - echo "Running Snyk scan..."
    - npx snyk test --all-projects
  allow_failure: true

terraform-provision:
  stage: terraform
  script:
    - ./scripts/deploy-terraform.sh
  only:
    - new-portfolio-app
    - main

helm-deploy:
  stage: deploy
  script:
    - ./scripts/deploy-helm.sh
  only:
    - new-portfolio-app
    - main
  needs:
    - terraform-provision