apiVersion: ://coreos.com
kind: ServiceMonitor
metadata:
  name: nodejs-app-servicemonitor
  namespace: production
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: nodejs-multi-cloud-app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
